# Generated by Django 4.2.30 on 2026-04-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='address',
            field=models.CharField(blank=True, help_text='General location or street address', max_length=255),
        ),
        migrations.AddField(
            model_name='trail',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=90, help_text='Estimated time in minutes for filtering'),
        ),
        migrations.AddField(
            model_name='trail',
            name='location_name',
            field=models.CharField(blank=True, help_text='Trailhead, park, or neighborhood', max_length=200),
        ),
    ]
