# Generated by Django 6.0.2 on 2026-03-02 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('type_id', models.AutoField(db_column='typeid', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='typename', max_length=50)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'biketypes',
            },
        ),
        migrations.CreateModel(
            name='RentalLocation',
            fields=[
                ('location_id', models.AutoField(db_column='locationid', primary_key=True, serialize=False)),
                ('location_name', models.CharField(db_column='locationname', max_length=100)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('state', models.CharField(db_column='state', max_length=2)),
                ('zip_code', models.CharField(db_column='zipcode', max_length=10)),
                ('phone_number', models.CharField(blank=True, db_column='phonenumber', max_length=20, null=True)),
            ],
            options={
                'db_table': 'rentallocations',
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('trail_id', models.AutoField(db_column='trailid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('distance', models.DecimalField(blank=True, db_column='distance', decimal_places=2, max_digits=5, null=True)),
                ('difficulty', models.CharField(blank=True, db_column='difficulty', max_length=20, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'trails',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100, unique=True)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.AutoField(db_column='bikeid', primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, db_column='size', max_length=20, null=True)),
                ('hourly_rate', models.DecimalField(db_column='hourlyrate', decimal_places=2, max_digits=10)),
                ('status', models.CharField(db_column='status', default='Available', max_length=20)),
                ('type', models.ForeignKey(db_column='typeid', on_delete=django.db.models.deletion.PROTECT, to='pricing.biketype')),
                ('location', models.ForeignKey(db_column='locationid', on_delete=django.db.models.deletion.PROTECT, to='pricing.rentallocation')),
            ],
            options={
                'db_table': 'bikes',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(db_column='reservationid', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_column='startdate')),
                ('end_date', models.DateTimeField(db_column='enddate')),
                ('total_cost', models.DecimalField(blank=True, db_column='totalcost', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(db_column='status', default='Upcoming', max_length=20)),
                ('rating', models.IntegerField(blank=True, db_column='rating', null=True)),
                ('review_text', models.TextField(blank=True, db_column='reviewtext', null=True)),
                ('booking_date', models.DateTimeField(db_column='bookingdate')),
                ('bike', models.ForeignKey(blank=True, db_column='bikeid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.bike')),
                ('location', models.ForeignKey(blank=True, db_column='locationid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.rentallocation')),
                ('trail', models.ForeignKey(blank=True, db_column='trailid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.trail')),
                ('user', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.user')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
