# Generated by Django 5.2.11 on 2026-03-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessory_id', models.AutoField(db_column='accessoryid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'accessories',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('promo_code_id', models.AutoField(db_column='promocodeid', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('expiry_date', models.DateField(blank=True, db_column='expirydate', null=True)),
                ('is_active', models.BooleanField(db_column='isactive', default=True)),
            ],
            options={
                'db_table': 'promocodes',
            },
        ),
    ]
