# Generated by Django 5.2.11 on 2026-03-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_accessory_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories'},
        ),
    ]
