# Generated by Django 6.0.3 on 2026-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_alter_accessory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="is_available",
            field=models.BooleanField(db_column="available", default=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="name",
            field=models.CharField(
                db_column="name", default="Standard Bike", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="biketype",
            name="category",
            field=models.CharField(
                choices=[("Adult", "Adult"), ("Kids", "Kids")],
                default="Adult",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trail",
            name="zip_code",
            field=models.CharField(
                blank=True, db_column="zipcode", max_length=10, null=True
            ),
        ),
    ]
