# Generated by Django 6.0.3 on 2026-04-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("reservations", "0002_alter_reservation_bike_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="unlock_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
