# Generated by Django 6.0.3 on 2026-04-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_reservation_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="rental_duration",
            field=models.PositiveIntegerField(
                default=1, help_text="Duration in hours or days"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="special_requests",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
