# Generated by Django 6.0.3 on 2026-04-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_alter_reservation_admin_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="accessories",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="admin_notes",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
