# Generated by Django 4.2.29 on 2026-04-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_remove_reservation_accessories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for logistics/maintenance staff.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="special_requests",
            field=models.TextField(
                blank=True, help_text="Customer requests from checkout.", null=True
            ),
        ),
    ]
