# Generated by Django 4.2.29 on 2026-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_alter_accessory_price'),
        ('reservations', '0007_reservation_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationaccessory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservationaccessory',
            name='fulfillment_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('purchase', 'Purchase')], default='rental', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reservationaccessory',
            unique_together={('reservation', 'accessory', 'fulfillment_type')},
        ),
    ]
