# Generated by Django 4.2.29 on 2026-04-14 02:31

from datetime import timedelta
from decimal import Decimal

from django.db import migrations
from django.utils import timezone


def add_happybirthday_promo(apps, schema_editor):
    PromoCode = apps.get_model('reservations', 'PromoCode')
    now = timezone.now()
    PromoCode.objects.update_or_create(
        code='HAPPYBIRTHDAY',
        defaults={
            'description': 'Free bike rental during your birthday month. Accessories are not discounted.',
            'discount_type': 'percentage',
            'discount_value': Decimal('100.00'),
            'valid_from': now - timedelta(days=1),
            'valid_until': now + timedelta(days=3650),
            'max_uses': None,
            'current_uses': 0,
            'is_active': True,
            'minimum_order': Decimal('0.00'),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservationaccessory_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(add_happybirthday_promo, migrations.RunPython.noop),
    ]
