# Generated by Django 4.2.29 on 2026-04-14 02:44

from datetime import datetime
from decimal import Decimal

from django.db import migrations
from django.utils import timezone


def add_spring_promo_codes(apps, schema_editor):
    PromoCode = apps.get_model('reservations', 'PromoCode')

    promos = [
        {
            'code': 'SPRINGRIDE',
            'description': 'Celebrate spring with fresh air and a discounted ride.',
            'discount_type': 'percentage',
            'discount_value': Decimal('15.00'),
            'minimum_order': Decimal('40.00'),
            'valid_from': timezone.make_aware(datetime(2026, 3, 1, 0, 0)),
            'valid_until': timezone.make_aware(datetime(2026, 5, 31, 23, 59)),
            'max_uses': None,
        },
        {
            'code': 'SUNNYRIDE',
            'description': 'Perfect weather = perfect ride.',
            'discount_type': 'fixed',
            'discount_value': Decimal('8.00'),
            'minimum_order': Decimal('35.00'),
            'valid_from': timezone.make_aware(datetime(2026, 3, 1, 0, 0)),
            'valid_until': timezone.make_aware(datetime(2026, 10, 31, 23, 59)),
            'max_uses': None,
        },
        {
            'code': 'SEASONSTART',
            'description': 'Kick off the riding season.',
            'discount_type': 'percentage',
            'discount_value': Decimal('20.00'),
            'minimum_order': Decimal('0.00'),
            'valid_from': timezone.make_aware(datetime(2026, 3, 1, 0, 0)),
            'valid_until': timezone.make_aware(datetime(2026, 5, 31, 23, 59)),
            'max_uses': 50,
        },
        {
            'code': 'EGGRIDE',
            'description': 'Short-term Easter spring ride discount.',
            'discount_type': 'fixed',
            'discount_value': Decimal('10.00'),
            'minimum_order': Decimal('0.00'),
            'valid_from': timezone.make_aware(datetime(2026, 4, 1, 0, 0)),
            'valid_until': timezone.make_aware(datetime(2026, 4, 19, 23, 59)),
            'max_uses': None,
        },
        {
            'code': 'WEEKDAYRIDE',
            'description': 'Save on slower weekday rides.',
            'discount_type': 'percentage',
            'discount_value': Decimal('20.00'),
            'minimum_order': Decimal('0.00'),
            'valid_from': timezone.make_aware(datetime(2026, 1, 1, 0, 0)),
            'valid_until': timezone.make_aware(datetime(2026, 12, 31, 23, 59)),
            'max_uses': None,
        },
        {
            'code': 'RIDETOGETHER',
            'description': 'Bring a friend and save.',
            'discount_type': 'fixed',
            'discount_value': Decimal('12.00'),
            'minimum_order': Decimal('0.00'),
            'valid_from': timezone.make_aware(datetime(2026, 1, 1, 0, 0)),
            'valid_until': timezone.make_aware(datetime(2026, 12, 31, 23, 59)),
            'max_uses': None,
        },
    ]

    for promo in promos:
        PromoCode.objects.update_or_create(
            code=promo['code'],
            defaults={
                **promo,
                'current_uses': 0,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_add_happybirthday_promo'),
    ]

    operations = [
        migrations.RunPython(add_spring_promo_codes, migrations.RunPython.noop),
    ]
