# Generated by Django 6.0.2 on 2026-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_add_spring_promo_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="rating",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
    ]
