# Generated by Django 6.0.2 on 2026-04-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0011_reservation_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="rating",
        ),
    ]
