# Generated by Django 4.2.29 on 2026-04-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible to staff only.'),
        ),
    ]
