# Generated by Django 6.0.2 on 2026-04-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_admin_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accent_color",
            field=models.CharField(default="#2ecc71", max_length=7),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(default="light", max_length=10),
        ),
    ]
