# Generated by Django 6.0.2 on 2026-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_accent_color_user_avatar_user_cover_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="accent_color",
        ),
        migrations.RemoveField(
            model_name="user",
            name="theme",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_quote",
            field=models.TextField(blank=True, null=True),
        ),
    ]
