# Generated by Django 5.2.11 on 2026-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdat'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(db_column='paymentid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Mock', 'Mock'), ('Card', 'Card'), ('Cash', 'Cash'), ('Online', 'Online')], db_column='paymentmethod', default='Mock', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_column='paymentdate', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation_id',
            field=models.IntegerField(db_column='reservationid', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], db_column='status', default='Pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
