# Generated by Django 6.0.3 on 2026-04-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="available_docks",
        ),
        migrations.RemoveField(
            model_name="location",
            name="total_docks",
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="total_slots",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="location",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
