# Generated by Django 4.2.29 on 2026-04-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_remove_location_available_docks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="station_number",
            field=models.IntegerField(default=0),
        ),
    ]
