# Generated by Django 4.2.29 on 2026-03-15 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('comfort', 'Comfort'), ('storage', 'Storage'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('is_available', models.BooleanField(default=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bike Category',
                'verbose_name_plural': 'Bike Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BikeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inches', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(help_text='Description of who this size fits')),
                ('recommended_height', models.CharField(help_text='Recommended rider height range', max_length=100)),
                ('recommended_age', models.CharField(blank=True, help_text='Recommended age range', max_length=100)),
            ],
            options={
                'ordering': ['size_inches'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('bike_type', models.CharField(choices=[('adult', 'Adult Bike'), ('kids', 'Kids Bike'), ('mountain', 'Mountain Bike')], max_length=20)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='List key features, one per line')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_maintenance', models.BooleanField(default=False, help_text='Bike is under maintenance')),
                ('maintenance_note', models.TextField(blank=True, help_text='Reason for maintenance')),
                ('quantity_total', models.PositiveIntegerField(default=1, help_text='Total bikes of this model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.bikecategory')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to='bikes.bikesize')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BikeAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommended', models.BooleanField(default=False)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_bikes', to='bikes.accessory')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_accessories', to='bikes.bike')),
            ],
            options={
                'verbose_name': 'Bike Accessory',
                'verbose_name_plural': 'Bike Accessories',
                'unique_together': {('bike', 'accessory')},
            },
        ),
    ]
