# Generated by Django 6.0.3 on 2026-04-02 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0001_initial"),
        ("locations", "0002_remove_location_available_docks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bikes",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "At Dock"),
                    ("in_use", "On Trail"),
                    ("maintenance", "In Shop"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
