# Generated by Django 6.0.3 on 2026-04-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0002_bike_location_bike_status"),
        ("locations", "0002_remove_location_available_docks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bikes",
                to="locations.location",
            ),
        ),
    ]
