# Generated by Django 6.0.3 on 2026-04-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0003_alter_bike_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessory",
            name="price",
        ),
    ]
