# Generated by Django 4.2.29 on 2026-04-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0004_remove_accessory_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessory",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="bike",
            name="status",
            field=models.CharField(
                choices=[
                    ("maintenance", "At Dock"),
                    ("in_use", "On Trail"),
                    ("available", "In Shop"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
