# Generated by Django 4.2.29 on 2026-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0005_accessory_price_alter_bike_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Unique ID for this physical unit (e.g., ICC-101)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
