# Generated by Django 4.2.29 on 2026-04-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0006_bike_serial_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bike",
            name="quantity_total",
        ),
    ]
