# Generated by Django 4.2.29 on 2026-04-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_accessory_price'),
        ('bikes', '0007_remove_bike_quantity_total'),
    ]

    operations = [
    ]
