# Generated by Django 4.2.29 on 2026-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikes", "0007_remove_bike_quantity_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="bike_type",
            field=models.CharField(
                choices=[
                    ("adult", "Adult Bike"),
                    ("kids", "Kids Bike"),
                    ("mountain", "Mountain Bike"),
                    ("tandem", "Tandem Bike"),
                ],
                max_length=20,
            ),
        ),
    ]
