# Generated by Django 4.2.29 on 2026-04-14 02:24

from django.db import migrations, models


def mark_universal_accessories(apps, schema_editor):
    Accessory = apps.get_model('bikes', 'Accessory')
    universal_names = [
        'Helmet - Adult',
        'Helmet - Youth',
        'Helmet - Child',
        'Cage for Water bottles',
        'Disposable Poncho',
        'Gel Seat Cover',
        'Phone Mount',
        'Baby Seat',
        'Child Trailer',
        'Bike Lights Set',
        'Bike Lock',
        'Bike Basket',
        'Handlebar Bag',
        'Rear Rack Bag',
    ]
    Accessory.objects.filter(name__in=universal_names).update(is_universal=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_alter_accessory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_universal',
            field=models.BooleanField(default=False, help_text='Show this accessory for every bike reservation.'),
        ),
        migrations.RunPython(mark_universal_accessories, migrations.RunPython.noop),
    ]
