# Generated by Django 4.2.30 on 2026-04-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_alter_bike_bike_type'),
        ('bikes', '0010_accessory_is_universal'),
    ]

    operations = [
    ]
